Replace `Time.zone.current` with `Time.current` on Rails::TimeZone message
The default message for the `flexible` style mentions `Time.zone.current`
(e.g. "Do not use `Time.now` without zone. Use one of `Time.zone.now`,
`Time.zone.current`, `Time.now.in_time_zone`, `Time.now.utc`, `Time.now.getlocal`,
`Time.now.iso8601`, `Time.now.jisx0301`, `Time.now.rfc3339`, `Time.now.to_i`,
`Time.now.to_f` instead.").

Calling `Time.zone.current` causes a `NoMethodError` since there's no `current`
method on `ActiveSupport::TimeZone`. Instead, the message should mention
`Time.current`, which is probably the intended call that takes the time zone in
account.

With this change the message would change to "Do not use `Time.now` without
zone. Use one of `Time.zone.now`, `Time.current`, `Time.now.in_time_zone`,
`Time.now.utc`, `Time.now.getlocal`, `Time.now.iso8601`, `Time.now.jisx0301`,
`Time.now.rfc3339`, `Time.now.to_i`, `Time.now.to_f` instead."

```
[12] pry(main)> Time.now
=> 2015-11-26 16:51:59 -0500
[13] pry(main)> Time.zone.now
=> Thu, 26 Nov 2015 21:52:02 UTC +00:00
[14] pry(main)> Time.current
=> Thu, 26 Nov 2015 21:52:08 UTC +00:00
[15] pry(main)> Time.zone.current
NoMethodError: undefined method `current' for #<ActiveSupport::TimeZone:0x007f81a08e1380>
from (pry):15:in `<main>'
```