Add new `Lint/SafeNavigationChain` cop
Safe navigation operator returns nil if the receiver is nil.
So if you chain an ordinary method call after safe navigation operator, it raises NoMethodError.
We should use safe navigation operator after safe navigation operator.
This cop checks the problem.

For example

```ruby
x = nil
x&.foo.bar   # => NoMethodError: undefined method `bar' for nil:NilClass
x&.foo&.bar  # => nil
```