Improve failure messages for unconfigured new cops
There's a neat spec which ensures that all cops are included in the
default configuration. I had two failures when adding the
CircularArgumentReference cop. It wasn't *too* hard to figure out what
to do, but these changes should make it more obvious how to trace the
error.

Using #fetch instead of #[] means our error changes from:
  NoMethodError:
    undefined method `[]' for nil:NilClass
to:
  KeyError:
    key not found: "Lint/CircularArgumentReference"

Using #match_array instead of #eq means the other error changes from:
  expected <GIANT ARRAY>
  got <OTHER GIANT ARRAY>
  (compared using ==)

to:
  expected <GIANT ARRAY>
  got <OTHER GIANT ARRAY>
  the missing elements were ["Lint/CircularArgumentReference"]