Warn about obsolete cops and parameters
This change improves obsolete warnings in three ways.

1. Show all obsoletes
--------

Currently, RuboCop displays first obsolete warning only.

```yaml
 # two obsolete cops
Style/SingleSpaceBeforeFirstArg:
  Enabled: false
Style/SpaceBeforeModifierKeyword:
  Enabled: false
```

```
Error: The `Style/SingleSpaceBeforeFirstArg` cop has been renamed to `Style/SpaceBeforeFirstArg.
(obsolete configuration found in /tmp/tmp.9T2ers7SW8/.rubocop.yml, please update it)
```

This change makes to display all obsolete warnings.

```
Error: The `Style/SingleSpaceBeforeFirstArg` cop has been renamed to `Style/SpaceBeforeFirstArg.`
(obsolete configuration found in /tmp/tmp.9T2ers7SW8/.rubocop.yml, please update it)
The `Style/SpaceBeforeModifierKeyword` cop has been removed. Please use `Style/SpaceAroundKeyword` instead.
(obsolete configuration found in /tmp/tmp.9T2ers7SW8/.rubocop.yml, please update it)
```

2. Add obsolete cops
---------

`Style/MethodCallParentheses` and `Lint/Eval` are renamed.
- #3797
- #3820

So, I added the cops to `OBSOLATE_COPS`.

3. Add obsolete parameters

In #3765, some cop's parameters are renamed.

So, I added the parameters to `OBSOLATE_PARAMETERS`