Remove unused argument for `format` in `Security/YAMLLoad` cop
With `ruby -w`, a warning is occurred in `Security/YAMLLoad` cop.

```sh
$ RUBYOPT=-w
/home/pocke/.gem/ruby/2.4.0/gems/parser-2.3.3.1/lib/parser/lexer.rb:10922: warning: assigned but unused variable - testEof
/home/pocke/.gem/ruby/2.4.0/gems/rubocop-0.47.1/lib/rubocop/magic_comment.rb:124: warning: `frozen_string_literal' is ignored after any tokens
Inspecting 888 files
............................/home/pocke/.gem/ruby/2.4.0/gems/rubocop-0.47.1/lib/rubocop/cop/security/yaml_load.rb:27: warning: too many arguments for format string
........................................................................................................................................................................................................................................................................................................................................................................................................................................................./home/pocke/.gem/ruby/2.4.0/gems/rubocop-0.47.1/lib/rubocop/cop/security/yaml_load.rb:27: warning: too many arguments for format string
...................................................................................................................................................................................................................................................................................................................................................................................................................................

888 files inspected, no offenses detected
```

The argument is not used. So, I've remove it.

Note
-----

Other warnings are occurred, however, this change ignores the warnings.

- `/home/pocke/.gem/ruby/2.4.0/gems/parser-2.3.3.1/lib/parser/lexer.rb:10922: warning: assigned but unused variable - testEof`
  - It's a parser gem's problem.
- `/home/pocke/.gem/ruby/2.4.0/gems/rubocop-0.47.1/lib/rubocop/magic_comment.rb:124: warning: `frozen_string_literal' is ignored after any tokens`
  - It's a false positive.